#!/usr/bin/env python3
"""levels/*.json (the Unity game's keep files) -> src/levels.c

    python3 tools/levels2c.py      (from projects/spectral_keep)

Each room's ASCII layers become one string of MAXH * d * w cells, layer y,
row z (z = 0 is the front, as RoomData.Get), column x.
"""
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MAXH = 6
ACTORS = {"guard": 0, "hound": 1, "ghost": 2, "bouncer": 3, "sage": 4}
WALLS = {"brick": 0, "rock": 1}
FLOORS = {"slab": 0, "wood": 1, "cobble": 2}


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    out = ["/* generated by tools/levels2c.py from the JSON files in levels/ - do not edit */",
           '#include "keep.h"', ""]
    levels = []
    for li, path in enumerate(sorted(glob.glob(os.path.join(ROOT, "levels", "*.json")))):
        lv = json.load(open(path))
        rooms = lv["rooms"]
        ids = [r["id"] for r in rooms]
        for ri, r in enumerate(rooms):
            w, d = r["w"], r["d"]
            cells = [["."] * (w * d) for _ in range(MAXH)]
            for layer in r.get("layers", []):
                y = layer["y"]
                for row, line in enumerate(layer["rows"][:d]):
                    z = d - 1 - row
                    for x, ch in enumerate(line[:w]):
                        cells[y][z * w + x] = ch
            flat = "".join("".join(c) for c in cells)
            out.append(f"static const char cells_{li}_{ri}[] = {cstr(flat)};")
            acts = r.get("actors", [])
            if acts:
                out.append(f"static const KActor actors_{li}_{ri}[] = {{")
                for a in acts:
                    out.append(f"    {{ {ACTORS[a['type']]}, {a['x']}, {a['y']}, {a['z']}, "
                               f"{1 if a.get('axis', 'x') == 'z' else 0}, {cstr(a.get('text', '') or '')} }},")
                out.append("};")
        out.append(f"static const KRoom rooms_{li}[] = {{")
        for ri, r in enumerate(rooms):
            acts = r.get("actors", [])
            out.append(f"    {{ {cstr(r['id'])}, {cstr(r['name'])}, {r['gx']}, {r['gy']}, {r['w']}, {r['d']}, "
                       f"{r['ink']}, {cstr(r.get('seal', '') or '')}, {WALLS.get(r.get('wall'), 0)}, "
                       f"{FLOORS.get(r.get('floor'), 0)}, cells_{li}_{ri}, "
                       f"{'actors_%d_%d' % (li, ri) if acts else '0'}, {len(acts)} }},")
        out.append("};")
        start = ids.index(lv["startRoom"]) if lv.get("startRoom") in ids else 0
        levels.append(f"    {{ {cstr(lv['name'])}, {lv['relicsNeeded']}, {start}, {lv['startX']}, "
                      f"{lv['startY']}, {lv['startZ']}, rooms_{li}, {len(rooms)} }},")
    out.append("")
    out.append("const KLevel keep_levels[] = {")
    out += levels
    out.append("};")
    out.append(f"const int keep_nlevels = {len(levels)};")
    open(os.path.join(ROOT, "src", "levels.c"), "w").write("\n".join(out) + "\n")
    print(f"wrote src/levels.c: {len(levels)} keeps")


if __name__ == "__main__":
    main()
